// Generated by CoffeeScript 1.8.0

/* Beep Boop */


/*
console.log "beep boop"
 */


/*Meet Pipe */


/*
fs = require 'fs'

file = process.argv[2]

fs.createReadStream(file).pipe(process.stdout)
 */


/*Input Output */


/*
process.stdin.pipe(process.stdout)
 */


/*Transform */

(function() {
  var through, tr;

  through = require('through');

  tr = through(function(buf) {
    return this.queue(buf.toString().toUpperCase());
  });

  process.stdin.pipe(tr).pipe(process.stdout);

}).call(this);
