// Generated by CoffeeScript 1.8.0

/* Beep Boop */


/*
console.log "beep boop"
 */


/*Meet Pipe */


/*
fs = require 'fs'

file = process.argv[2]

fs.createReadStream(file).pipe(process.stdout)
 */


/*Input Output */


/*
process.stdin.pipe(process.stdout)
 */


/*Transform */


/*
through = require 'through'
tr = through (buf) -> 
  this.queue(buf.toString().toUpperCase())

process.stdin.pipe(tr).pipe(process.stdout)
 */


/*Lines */

(function() {
  var lineCount, split, through, tr;

  split = require('split');

  through = require('through');

  lineCount = 0;

  tr = through(function(buf) {
    var line;
    line = buf.toString();
    if (lineCount % 2 === 0) {
      this.queue(line.toLowerCase() + '\n');
    } else {
      this.queue(line.toUpperCase() + '\n');
    }
    return lineCount++;
  });

  process.stdin.pipe(split()).pipe(tr).pipe(process.stdout);

}).call(this);
